name: Tests
on: [push]

jobs:
  
  build:
    
    name: Try compiling on windows
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
       
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip

    - name: Install readItAndKeep
      run: |
        git clone https://github.com/GenomePathogenAnalysisService/read-it-and-keep.git
        cd read-it-and-keep
        cd src
        make
        mv readItAndKeep ../..
        cd ../..
        rm -r read-it-and-keep

    - name: Install samtools
      run: |      
         $source = 'https://github.com/samtools/samtools/releases/download/1.14/samtools-1.14.tar.bz2'
         $destination = 'samtools-1.14.tar.bz2'
         Invoke-WebRequest -Uri $source -OutFile $destination
         7z x -tbzip2 samtools-1.14.tar.bz2
         tar xvf samtools-1.14.tar
         cd samtools-1.14
         ./configure
         make
         cp samtools ..
         cd ..

    - name: Test with pytest
      run: |
        pytest --exitfirst --verbose --failed-first \
        --cov=. --cov-report html tests/
